### ISSUE TITLE
HMR failling because of Access-Control-Allow-Origin

### ISSUE THREAD

**Issue by iamandrewluca** [verekia/js-stack-from-scratch#207] opened 2017-04-22 17:56 UTC
### If it's a bug:
```
[WDS] App updated. Recompiling...
[WDS] App hot update...
[HMR] Checking for updates on the server...
XMLHttpRequest cannot load http://localhost:7000/dist/ffacf69653bfa6a58a17.hot-update.json.
No 'Access-Control-Allow-Origin' header is present on the requested resource.
Origin 'http://localhost:8000' is therefore not allowed access.
```

### Fix:
Add to `webpack.config.babel.js`
```
devServer: {
  // ...
  headers: { 'Access-Control-Allow-Origin': '*' }
}
```

![image](https://cloud.githubusercontent.com/assets/1881266/25306820/04e911d4-279e-11e7-91be-c3cd940e59b4.png)

**Comment by samgranieri** [comment] 2017-04-25 02:22
This worked for me

**Comment by iamandrewluca** [comment] 2017-04-25 09:13
Maybe is related to browser environment.

**Comment by iamandrewluca** [comment] 2017-04-25 21:49
I don't know why this happened. Now I can't reproduce this problem.

**Comment by iamandrewluca** [comment] 2017-04-25 21:53
Sorry for reopening. I will close it for now.

**Comment by umaulana** [comment] 2017-04-30 16:26
I encountered same issue

**Comment by Myoursky** [comment] 2017-05-03 03:15
I encountered same issue,but with the [official code ](https://github.com/verekia/js-stack-walkthrough/tree/master/04-webpack-react-hmr),I can't reproduce this problem.

**Comment by verekia** [comment] 2017-05-03 05:04
It is likely due to a more recent of Webpack Dev Server than the one I used in the walkthrough. I will update the tutorial asap. Sorry about that!

**Comment by zcntpz** [comment] 2017-05-03 17:57
webpack.config.babel.js add 
`
devServer: { 
  headers: { 
    'Access-Control-Allow-Origin': 'http://localhost:8000'
  }
}
` 
to fix

**Comment by crisisdesign** [comment] 2017-05-08 23:22
a better aproach could be import the web port from "./src/shared/config":

import { WDS_PORT, WEB_PORT } from './src/shared/config'
// [...]
devServer: { headers: { 'Access-Control-Allow-Origin': `http://localhost:${WEB_PORT}` }, },

**Comment by JiangdandanAbigale** [comment] 2017-05-19 09:39
thanks.

**Comment by lavebug** [comment] 2017-05-19 16:02
headers: { 'Access-Control-Allow-Origin': '*' } in webpack.config.babel.js worked. Thanks

**Comment by verekia** [comment] 2017-05-22 20:12
It's fixed in the latest version of the tutorial.
Thanks everyone :)

**Closed by verekia** 2017-05-22 20:12 UTC
Labels: bug

**Comment by jerryOnlyZRJ** [comment] 2019-07-09 03:22
Thank you! It works for me! 🎉
