### ISSUE TITLE
Error: Command failed: node lib

### ISSUE THREAD

**Issue by sgatlf** [verekia/js-stack-from-scratch#52] opened 2016-10-31 06:14 UTC
After adding:
```
    "env": {
      "browser": true
    }
```
I received the error:

> Error: Command failed: node lib
> module.js:474
>     throw err;
>     ^
> 
> Error: Cannot find module

I cannot go past this step and I have went back and checked my code. Everything matches accordingly.

**Comment by verekia** [comment] 2016-10-31 06:16
You likely haven't compiled your `src` folder into the `lib` folder via Gulp / Babel before running `node lib`.

**Comment by sgatlf** [comment] 2016-10-31 06:22
Doesn't gulp do this with build?

**Comment by verekia** [comment] 2016-10-31 06:27
Yes it does it, but maybe you're missing something in your Gulp file like prerequisite tasks.

**Comment by verekia** [comment] 2016-10-31 06:28
Compare the provided Gulp file with yours and you should find the difference :)

**Comment by sgatlf** [comment] 2016-10-31 06:47
The provided Gulp file is finished for Section 7. But I compared with the gulp file on section 6 and my file is exact.

```
/* eslint-disable import/no-extraneous-dependencies */
/* eslint-disable no-console */

import gulp from 'gulp';
import babel from 'gulp-babel';
import eslint from 'gulp-eslint';
import del from 'del';
import { exec } from 'child_process';

const paths = {
  allSrcJs: 'src/**/*.js',
  gulpFile: 'gulpfile.babel.js',
  libDir: 'lib',
};

gulp.task('lint', () =>
  gulp.src([
    paths.allSrcJs,
    paths.gulpFile,
  ])
    .pipe(eslint())
    .pipe(eslint.format())
    .pipe(eslint.failAfterError())
);

gulp.task('clean', () => del(paths.libDir));

gulp.task('build', ['lint', 'clean'], () =>
  gulp.src(paths.allSrcJs)
    .pipe(babel())
    .pipe(gulp.dest(paths.libDir))
);

gulp.task('main', ['build'], (callback) => {
  exec(`node ${paths.libDir}`, (error, stdout) => {
    console.log(stdout);
    return callback(error);
  });
});

gulp.task('watch', () => {
  gulp.watch(paths.allSrcJs, ['main']);
});

gulp.task('default', ['watch', 'main']);

```

**Comment by sgatlf** [comment] 2016-10-31 07:07
I just kept going and since lib is not referenced after webpack the errors are gone. I am working on a windows machine so there could be an issue due to different environment.

**Comment by lxblvs** [comment] 2016-10-31 12:31
Same problem on a linux machine.

The weird bit in the error is 

`Error: Cannot find module '/home/alex/thingies/js-test/lib'
`

I have the lib module in the root. Is it something about the task ordering? Here is my gulpfile:

```
/* eslint-disable import/no-extraneous-dependencies */

import gulp from 'gulp';
import babel from 'gulp-babel';
import del from 'del';
import { exec } from 'child_process';
import eslint from 'gulp-eslint';


const paths = {
    allSrcJs: 'src/**/*.js',
    gulpFile: 'gulpfile.babel.js',
    libDir: 'lib',
};

gulp.task('clean', () =>
    del(paths.libDir)
);

gulp.task('build', ['lint', 'clean'], () =>
    gulp.src(paths.allSrcJs)
        .pipe(babel())
        .pipe(gulp.dest(paths.libDir))
);

gulp.task('main', ['build'], (callback) => {
    exec(`node ${paths.libDir}`, (error, stdout) => {
        console.log(stdout);
        return callback(error);
    });
});

gulp.task('watch', () => {
    gulp.watch([paths.allSrcJs, paths.gulpFile], ['main']);
});

gulp.task('default', ['watch', 'main']);

gulp.task('lint', () =>
    gulp.src([
        paths.allSrcJs,
    ])
        .pipe(eslint())
        .pipe(eslint.format())
        .pipe(eslint.failAfterError())
);
```

**Comment by verekia** [comment] 2016-10-31 13:07
Okay, I was able to reproduce the issue.

The problem is that you need to go further in that chapter to reach a build-able state. It is still in the middle of setting things up, and the build is not expected to work at every intermediate state such as this one. Just keep following instructions and you'll get a working build soon enough :)

**Comment by verekia** [comment] 2016-10-31 13:19
Closing for now. If more people keep getting confused with the build not working at such intermediate states, I'll change the readme to make it clearer. If you're one of these people, please upvote @sgatlf's original comment!

**Closed by verekia** 2016-10-31 13:19 UTC
